// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  navigation: dynamic(() => import('./Navigation')),
  navigation_annoncement: dynamic(() => import('./Annoncement')),
  product_header: dynamic(() => import('./ProductHeader')),
  product_hightlight: dynamic(() => import('./ProductHightlight')),
};
