// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  collection_header: dynamic(() => import('./CollectionHeader')),
  product_grid: dynamic(() => import('./ProductGrid')),
  product_header: dynamic(() => import('./ProductHeader')),
  product_hightlight: dynamic(() => import('./ProductHightlight')),
};
