// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  product_header: dynamic(() => import('./ProductHeader')),
  product_hightlight: dynamic(() => import('./ProductHightlight')),
};
